language: java

sudo: false

cache:
 directories:
   - $HOME/.m2

jdk:
  - oraclejdk8

os:
  - linux

# Usually run the CI builds in offline mode.  If this is breaking the
# build, go ahead and remove offline mode (-o).

script: mvn -f edu.umaine.cs.hdfjavaio.parent/pom.xml clean verify
